services:
  mqtt:
    image: eclipse-mosquitto:2.0.21
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto-conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto-conf/passwd:/mosquitto/config/passwd
    restart: always
    networks:
      - private-network

  subscriber:
    image: us-central1-docker.pkg.dev/erudite-nation-440421-p7/dblocks/subscriber:v1
    depends_on:
      - mqtt
    restart: on-failure
    environment:
      - MONGO_URI
      - MQTT_HOST
      - MQTT_USER
      - MQTT_PASS
    networks:
      - private-network

  publisher:
    image: us-central1-docker.pkg.dev/erudite-nation-440421-p7/dblocks/publisher:v1
    depends_on:
      - mqtt
    restart: unless-stopped
    environment:
      - MQTT_HOST
      - MQTT_USER
      - MQTT_PASS
    networks:
      - private-network

networks:
  private-network:
    external: true
