# Dockerfile-ui
FROM httpd:latest

WORKDIR /usr/local/apache2/htdocs

# Copia apenas o conteúdo da pasta ui/ para o DocumentRoot
COPY ui/ ./

# Opcional: define o ServerName
RUN echo "ServerName localhost" >> /usr/local/apache2/conf/httpd.conf

EXPOSE 80

CMD ["httpd", "-D", "FOREGROUND"]
