services:
  api:
    container_name: api
    image: us-central1-docker.pkg.dev/erudite-nation-440421-p7/dblocks/api:v2
    ports:
      - "3000:8080"
    depends_on:
      - mqtt
    environment:
      - MQTT_HOST
      - MQTT_USER
      - MQTT_PASS
      - MONGO_URI=mongodb+srv://ti:HjrjfpzWT4cdDJqc@bipes-db.wlo1lu9.mongodb.net/?retryWrites=true&w=majority&appName=bipes-db
    networks:
      - private-network

  ui:
    container_name: ui
    image: us-central1-docker.pkg.dev/erudite-nation-440421-p7/dblocks/ui:v5
    ports:
      - "80:80"
      - "443:443"
    networks:
      - private-network

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0.21
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto-conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto-conf/passwd:/mosquitto/config/passwd
    restart: always
    networks:
      - private-network

  subscriber:
    container_name: subscriber
    image: us-central1-docker.pkg.dev/erudite-nation-440421-p7/dblocks/subscriber:v2
    depends_on:
      - mqtt
    restart: on-failure
    environment:
      - MONGO_URI=mongodb+srv://ti:HjrjfpzWT4cdDJqc@bipes-db.wlo1lu9.mongodb.net/?retryWrites=true&w=majority&appName=bipes-db
      - MQTT_HOST
      - MQTT_USER
      - MQTT_PASS
    networks:
      - private-network

  publisher:
    container_name: publisher
    image: us-central1-docker.pkg.dev/erudite-nation-440421-p7/dblocks/publisher:v1
    depends_on:
      - mqtt
    restart: unless-stopped
    environment:
      - MQTT_HOST
      - MQTT_USER
      - MQTT_PASS
    networks:
      - private-network

networks:
  private-network:
    external: true
