version: "3.8"

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile-ui
    ports:
      - "8080:80"   
    restart: always

  api:
    build:
      context: ./easymqtt
      dockerfile: Dockerfile   #Dockerfile PHP
    ports:
      - "3000:80"
    #depends_on:
      #- mongo
    restart: always

  mqtt:
    image: eclipse-mosquitto:2.0.21
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto-conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  #mongo:
    #image: mongo
    #ports:
     # - "27017:27017"
    #restart: always
  
  subscriber:
    build:
      context: ./easymqtt
      dockerfile: Dockerfile-subscriber
    depends_on:
      - mqtt
      #- mongo
    restart: on-failure

  publisher:
    build:
      context: ./easymqtt
      dockerfile: Dockerfile-publisher
    depends_on:
      - mqtt
    restart: unless-stopped


