var MSG = {
  title: "BIPES",
  blocks: "Blocchi",
  files: "File",
  shared: "Condiviso",
  device: "Dispositivo",
  linkTooltip: "Salva e collega ai blocchi.",
  runTooltip: "Esegui il programma definito dai blocchi nell'area di lavoro.",
  badCode: "Errore programma:\n%1",
  timeout:
    "È stato superato il numero massimo consentito di iterazioni eseguite.",
  trashTooltip: "Elimina tutti i blocchi.",
  catLogic: "Logica",
  catLoops: "Cicli",
  catMath: "Matematica",
  catText: "Testo",
  catLists: "Elenchi",
  catColour: "Colore",
  catVariables: "Variabili",
  catFunctions: "Funzioni",
  listVariable: "elenco",
  textVariable: "testo",
  httpRequestError: "La richiesta non è stata soddisfatta.",
  linkAlert: "Condividi i tuoi blocchi con questo collegamento:\n\n%1",
  hashError: "Mi spiace, '%1' non corrisponde ad alcun programma salvato.",
  xmlError:
    "Non è stato possibile caricare il documento. Forse è stato creato con una versione diversa di Blockly?",
  badXml:
    "Errore durante l'analisi XML:\n%1\n\nSeleziona 'OK' per abbandonare le modifiche o 'Annulla' per continuare a modificare l'XML.",
  saveTooltip: "Salva i blocchi su file.",
  loadTooltip: "Carica i blocchi da file.",
  notificationTooltip: "Pannello delle notifiche.",
  ErrorGET: "Impossibile caricare il file richiesto.",
  invalidDevice: "Dispositivo non valido.",
  languageTooltip: "Cambia lingua.",
  noToolbox: "Il dispositivo non ha una toolbox definita.",
  networkTooltip: "Connetti tramite rete (WebREPL, http).",
  serialTooltip:
    "Connetti tramite seriale/USB o Bluetooth (Web Serial API, https).",
  toolbarTooltip: "Mostra barra degli strumenti",
  wrongDevicePin: "Verifica i pin, il dispositivo di destinazione è cambiato!",
  notDefined: "non definito",
  editAsFileValue: "Modifica come file",
  editAsFileTooltip:
    "Modifica il codice Python e salvalo nel file system del dispositivo.",
  forumTooltip: "Forum di aiuto.",
  accountTooltip: "I tuoi progetti e impostazioni.",
  blocksLoadedFromFile: "Blocchi caricati dal file '%1'.",
  deviceUnavailable: "Dispositivo '%1' non disponibile.",
  notConnected: "Nessuna connessione per inviare dati.",
  serialFroozen: "La connessione seriale non risponde.",
  notAvailableFlag:
    "$1 non è disponibile nel tuo browser.\r\nAssicurati che il flag $1 sia abilitato.",

  // Blocchi
  block_delay: "ritardo",
  seconds: "secondi",
  milliseconds: "millisecondi",
  microseconds: "microsecondi",
  to: "a",
  setpin: "imposta pin di uscita",
  pin: "pin",
  read_digital_pin: "leggi ingresso digitale",
  read_analog_pin: "leggi ingresso analogico",
  show_iot: "mostra nella scheda IoT",
  data: "valore",
  set_rtc: "imposta data e ora",
  get_rtc: "ottieni data e ora",
  year: "anno",
  month: "mese",
  day: "giorno",
  hour: "ora",
  minute: "minuto",
  second: "secondo",
  wifi_scan: "scansiona reti wifi",
  wifi_connect: "connetti alla rete wifi",
  wifi_name: "nome della rete",
  wifi_key: "password/chiave",
  easymqtt_start: "Avvia EasyMQTT",
  easymqtt_publish: "Pubblica dati con EasyMQTT",
  topic: "argomento",
  session_id: "ID sessione",
  file_open: "apri file",
  file_name: "nome del file",
  file_mode: "modalità",
  file_binary: "apri in modalità binaria",
  file_close: "chiudi file",
  file_write_line: "scrivi riga nel file",
  file_line: "riga",
  try1: "prova",
  exp1: "eccetto",
  ntp_sync: "sincronizza data e ora con NTP",
  timezone: "fuso orario",
  project_info: "Informazioni progetto",
  project_info_author: "Autore",
  project_info_desc: "Descrizione",
  easymqtt_subscribe: "Sottoscrivi all'argomento EasyMQTT",
  when: "quando",
  data_received: "è ricevuto",
  easymqtt_receive: "Ricevi dati EasyMQTT",
  relay: "relè",
  on: "accendi",
  off: "spegni",
  relay_on: "relè sul pin",
  yes: "sì",
  no: "no",
  wait_for_data: "attendi dati",
  dht_start: "Avvia sensore DHT",
  dht_measure: "aggiorna lettura sensore DHT11/22",
  dht_temp: "ottieni temperatura DHT11/22",
  dht_humi: "ottieni umidità DHT11/22",
  type: "tipo",
  //Network
  net_http_get: "Richiesta HTTP GET",
  net_http_get_status: "Stato della risposta HTTP",
  net_http_get_content: "Contenuto della risposta HTTP",
  net_http_server_start: "Avvia server HTTP Web",
  net_http_server_start_port: "Porta",
  net_http_server_wait: "Attendi cliente HTTP",
  net_http_server_requested_page: "Pagina web richiesta",
  net_http_server_send_response: "Invia risposta HTTP",
  net_http_server_send_html: "HTML",

  //Splash screen
  splash_welcome: "Benvenuto in BIPES!",
  splash_footer: "Non mostrare più questa schermata",
  splash_close: "Chiudi",
  splash_message:
    "<p><b>BIPES: Block based Integrated Platform for Embedded Systems</B> consente di programmare, utilizzando testo o blocchi, diversi tipi di sistemi embedded e moduli per l'Internet delle Cose utilizzando MicroPython, CircuitPython, Linux o Snek. Puoi connetterti, programmare, eseguire il debug e monitorare vari tipi di schede utilizzando rete, wifi, USB o Bluetooth. Controlla l'elenco delle schede supportate <a href=https://bipes.net.br/wp/boards/>qui</a>. Alcuni esempi di schede compatibili sono: STM32, ESP32, ESP8266, Raspberry Pi (inclusa la Pico) e persino Arduino. <p><b>BIPES</b> è completamente <a href=https://bipes.net.br/wp/development/>aperto</a> e gratuito e funziona senza necessità di installare alcun plugin o software aggiuntivo, inoltre funziona offline, senza connessione a Internet. Speriamo che BIPES sia utile per te e che tu possa trarne vantaggio. Se hai bisogno di aiuto, abbiamo il <a href=https://github.com/BIPES/BIPES/discussions>forum di discussione</a>, dove <a href=https://github.com/BIPES/BIPES/discussions/categories/announcements>vengono anche annunciate novità</a>. Sentiti libero di partecipare e anche di lasciare commenti e suggerimenti per il progetto!</p><p>Carica MicroPython dal browser web, su ESP32 o ESP8266, facilmente per utilizzare BIPES: <a href=https://bipes.net.br/flash/esp-web-tools/>https://bipes.net.br/flash/esp-web-tools/</a></p><p>Scopri il libro di BIPES:<a href=https://bipes.net.br/wp/book-livro/>https://bipes.net.br/wp/book-livro/</a></p> <p>Il team del progetto BIPES ti ringrazia per il tuo interesse!</p>",
};

//Toolbox categories
Blockly.Msg["CAT_TIMING"] = "Temporizzazione";
Blockly.Msg["CAT_MACHINE"] = "Macchina";
Blockly.Msg["CAT_DISPLAYS"] = "Display";
Blockly.Msg["CAT_SENSORS"] = "Sensori";
Blockly.Msg["CAT_OUTPUTS"] = "Uscite e attuatori";
Blockly.Msg["CAT_COMM"] = "Comunicazione";
Blockly.Msg["CAT_FILES"] = "File";
Blockly.Msg["CAT_NET"] = "Rete e Internet";
Blockly.Msg["CAT_CONTROL"] = "Controllo";
