var MSG = {
  title: "BIPES",
  blocks: "Blokker",
  files: "Filer",
  shared: "Delt",
  device: "Enhet",
  linkTooltip: "Lagre og koble til blokkene.",
  runTooltip: "Kjør programmet definert av blokkene på arbeidsområdet.",
  badCode: "Feil i programmet:\n%1",
  timeout: "Maksimalt antall iterasjoner overskredet.",
  trashTooltip: "Slett alle blokker.",
  catLogic: "Logikk",
  catLoops: "Løkker",
  catMath: "Matematikk",
  catText: "Tekst",
  catLists: "Lister",
  catColour: "Farge",
  catVariables: "Variabler",
  catFunctions: "Funksjoner",
  listVariable: "liste",
  textVariable: "tekst",
  httpRequestError: "Det oppstod et problem med forespørselen.",
  linkAlert: "Del blokkene dine med denne lenken:\n\n%1",
  hashError: "Beklager, '%1' samsvarer ikke med et lagret program.",
  xmlError: "Kan ikke laste filen din. Kanskje den ble laget med en annen versjon av Blockly?",
  badXml: "XML-analysefeil:\n%1\n\nVelg 'OK' for å forkaste endringene eller 'Avbryt' for å redigere XML.",
  saveTooltip: "Lagre blokker til fil.",
  loadTooltip: "Last blokker fra fil.",
  notificationTooltip: "Varslingspanel.",
  ErrorGET: "Den forespurte filen ble ikke lastet.",
  invalidDevice: "Ugyldig enhet.",
  languageTooltip: "Endre språk.",
  noToolbox: "Enheten har ikke definert en verktøykasse.",
  networkTooltip: "Koble til via nettverk (WebREPL, http).",
  serialTooltip: "Koble til via seriell/USB eller Bluetooth (Web Serial API, https).",
  toolbarTooltip: "Vis verktøylinje",
  wrongDevicePin: "Sjekk pinnene, mål-enheten har endret seg!",
  notDefined: "ikke definert",
  editAsFileValue: "Rediger som fil",
  editAsFileTooltip: "Rediger python-kode og lagre til enhetens minne.",
  forumTooltip: "Hjelpeforum.",
  accountTooltip: "Dine prosjekter og miljøer.",
  blocksLoadedFromFile: "Blokker lastet fra filen '%1'.",
  deviceUnavailable: "Enhet '%1' er utilgjengelig.",
  notConnected: "Ingen tilkobling for å sende data.",
  serialFroozen: "Seriell tilkobling svarer ikke.",
  notAvailableFlag: "$1 er ikke tilgjengelig i nettleseren din.\r\nSørg for at flagget $1 er aktivert.",

  // Blokker
  block_delay: "vent",
  seconds: "sekunder",
  milliseconds: "millisekunder",
  microseconds: "mikrosekunder",
  to: "til",
  setpin: "sett utgangspin",
  pin: "pin",
  read_digital_pin: "les digital inngang",
  read_analog_pin: "les analog inngang",
  show_iot: "vis på IoT-fanen",
  data: "verdi",
  set_rtc: "sett dato og tid",
  get_rtc: "hent dato og tid",
  year: "år",
  month: "måned",
  day: "dag",
  hour: "time",
  minute: "minutt",
  second: "sekund",
  wifi_scan: "søk etter wifi-nettverk",
  wifi_connect: "koble til wifi-nettverk",
  wifi_name: "nettverksnavn",
  wifi_key: "passord/nøkkel",
  easymqtt_start: "start EasyMQTT",
  easymqtt_publish: "publiser data med EasyMQTT",
  topic: "emne",
  session_id: "Økt:",
  file_open: "åpne fil",
  file_name: "filnavn",
  file_mode: "modus",
  file_binary: "binær modus",
  file_close: "lukk fil",
  file_write_line: "skriv linje til fil",
  file_line: "linje",
  try1: "prøv",
  exp1: "ved feil",
  ntp_sync: "synkroniser dato og tid med NTP",
  timezone: "tidssone",
  project_info: "Prosjektinformasjon",
  project_info_author: "Forfatter",
  project_info_desc: "Beskrivelse",
  easymqtt_subscribe: "abonner på EasyMQTT-emne",
  easymqtt_receive: "motta EasyMQTT-data",
  when: "når",
  data_received: "er mottatt",
  relay: "relé",
  on: "på",
  off: "av",
  relay_on: "relé på pin",
  yes: "ja",
  no: "nei",
  wait_for_data: "vent på data",
  dht_start: "Start DHT11/22 sensor",
  dht_measure: "oppdater DHT11/22 sensoravlesning",
  dht_temp: "DHT11/22 temperatur",
  dht_humi: "DHT11/22 fuktighet",
  type: "modell",

  // Nettverk
  net_http_get: "HTTP GET-forespørsel",
  net_http_get_status: "HTTP svarstatus",
  net_http_get_content: "HTTP svarinnhold",
  net_http_server_start: "Start HTTP webserver",
  net_http_server_start_port: "Port",
  net_http_server_wait: "Vent på HTTP-klient",
  net_http_server_requested_page: "Etterspurt webside",
  net_http_server_send_response: "Send HTTP svar",
  net_http_server_send_html: "HTML",

  // Startskjerm
  splash_welcome: "Velkommen til BIPES!",
  splash_footer: "Ikke vis denne skjermen igjen",
  splash_close: "Lukk",
  splash_message: "<p><b>BIPES: Block based Integrated Platform for Embedded Systems</B> lar deg programmere, ved hjelp av tekst eller blokker, forskjellige typer innebygde systemer og moduler for tingenes internett ved hjelp av MicroPython, CircuitPython, Linux eller Snek. Du kan koble til, programmere, feilsøke og overvåke forskjellige typer kort ved hjelp av nettverk, wifi, USB eller Bluetooth. Se listen over støttede kort <a href=https://bipes.net.br/wp/boards/>her</a>. Noen eksempler på kompatible kort er: STM32, ESP32, ESP8266, Raspberry Pi (inkludert Pico) og til og med Arduino. <p><b>BIPES</b> er helt <a href=https://bipes.net.br/wp/development/>åpen</a> og gratis og fungerer uten behov for å installere noen plugin eller ekstra programvare, i tillegg til å fungere offline, uten internettforbindelse. Vi håper BIPES vil være nyttig for deg og at du vil ha glede av det. Hvis du trenger hjelp, har vi <a href=https://github.com/BIPES/BIPES/discussions>diskusjonsforum</a>, hvor <a href=https://github.com/BIPES/BIPES/discussions/categories/announcements>nyheter også kunngjøres</a>. Ikke nøl med å delta og også legge igjen kommentarer og forslag til prosjektet!</p><p>Brenn MicroPython direkte fra nettleseren på ESP32 eller ESP8266 enkelt for å bruke BIPES: <a href=https://bipes.net.br/flash/esp-web-tools/>https://bipes.net.br/flash/esp-web-tools/</a></p><p>Finn BIPES-boken:<a href=https://bipes.net.br/wp/book-livro/>https://bipes.net.br/wp/book-livro/</a></p> <p>BIPES-prosjektteamet takker for interessen din!</p>"
};

// Verktøykasse-kategorier
Blockly.Msg['CAT_TIMING'] = "Timing";
Blockly.Msg['CAT_MACHINE'] = "Maskin";
Blockly.Msg['CAT_DISPLAYS'] = "Skjermer";
Blockly.Msg['CAT_SENSORS'] = "Sensorer";
Blockly.Msg['CAT_OUTPUTS'] = "Utganger og aktuatorer";
Blockly.Msg['CAT_COMM'] = "Kommunikasjon";
Blockly.Msg['CAT_FILES'] = "Filer";
Blockly.Msg['CAT_NET'] = "Nettverk og Internett";
Blockly.Msg['CAT_CONTROL'] = "Kontroll";
